name: Quote Updater

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  Quote:
    name: Update Markdown Quote
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Using Quote workflow
        uses: oseveen/Quote@master
        with:
          commitMessage: 📖 Updating your profile with a new dream quote
          typeQuote: Dreams